# Stage 1: Build the React app
FROM node:18-alpine AS build

# Set working directory
WORKDIR /app

# Copy package files first (to leverage Docker's layer caching)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

ENV REACT_APP_BACKEND_URL=http://replace-with-fqdn:4000

# Build the React app
RUN npm run build

# Stage 2: Serve the production build with a lightweight server
FROM nginx:alpine

# Copy the production build from Stage 1
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 for the server
EXPOSE 80

# Start NGINX server
CMD ["nginx", "-g", "daemon off;"]
